### ISSUE TITLE
Does it suppose to work in Firefox?

### ISSUE THREAD

**Issue by ppaska** [zxbodya/angular-webpack-seed#2]
I am getting an error in FireFox v41.0.2 , while Chrome and MS Edge works fine

```
SyntaxError: let is a reserved identifier main.js:352:20
```

**Comment by zxbodya** [comment]
Yes, it should work in firefox too.

Very strange to see this error..

As far I know, how to get this error - it happens in cases like: trying define variable named `let` while running in `strict mode`. And it should also happen in all modern browsers...

Just tried in FF - it works for me...

**Comment by zxbodya** [comment]
Just tried to run project we were doing before(latest version I have) - seen that error…    

There is code `let _this = this;` in file `client/src/legacy/js/angular-dashboard-framework.js` at line 1124.
This file as all files from `legacy` was explicitly excluded from babel compilation, so all files there should be valid es5…  

To fix replace it by `var _this = this;`

**Comment by ppaska** [comment]
Thank for swift response. It solved the issue.
