### ISSUE TITLE
Block-scoped declarations

### ISSUE THREAD

**Issue by jjasonsparks** [zxbodya/angular-webpack-seed#4]
Running npm i as per ReadMe and am getting the classic SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode. node v5.11.1, npm v3.8.6.
Assuming I need to force strict mode.

**Comment by zxbodya** [comment]
There is a line in readme:
> Note: NodeJS 6+ is required.

**Comment by zxbodya** [comment]
Recently, because node js v6 supports almost all es2015 features, I have removed babel-node from tooling scripts (https://github.com/zxbodya/angular-webpack-seed/commit/7a3b9186c9447e22706a02c31eade8c122173598).

**Comment by jjasonsparks** [comment]
Thanks for the speedy response. nvm install 6, nvm use 6 works fine. All good. Thanks.
