### ISSUE TITLE
Karma sourcemap doesnt work

### ISSUE THREAD

**Issue by dmngu9** [zxbodya/angular-webpack-seed#5]
Your project skeleton is great. However, I noticed the Karma source map doesnt work. I modified 1 test to fail and this was what i gave me:

```
Expected [ Object({ title: 'Webpack', image: '/_karma_webpack_/8f29e53fcb774de5f113ee2206b328fe.png' }), Object({ title: 'Babel', image: '/_karma_webpack_/9d3f624715e9ce6a00ba6c3756027a14.png' }), Object({ title: 'Node Sass', image: '/_karma_webpack_/8c239efd2e25800bcca0fbab79373c1c.png' }) ] to be falsy.
	    at Object.<anonymous> (src/index.test.js:37162:30)
```

As you can see, it still refers to index.test.js not the test file. Im not sure if this is karma sourcemap loader issue?

**Comment by dmngu9** [comment]
I changed the devtool in karma config to inline-source-map. It works

**Comment by zxbodya** [comment]
thanks, for noticing this. updated karma configuration, to use inline-source-map.
