### ISSUE TITLE
Any plans for Typescript?

### ISSUE THREAD

**Issue by ppaska** [zxbodya/angular-webpack-seed#7]
Do you have any plans to integrate Typescript with AngularJS 1.* seed?
This could be a good stepping stone for Angular (4+) migration.

Thanks for doing great job!

**Comment by jhlagado** [comment]
Indeed. A wonderful job. Thanks for doing it.
 
I'm also looking for a Typescript option. Hopefully I will be able to add it to this project as a starting point.

**Comment by zxbodya** [comment]
Upgraded to Babel7. As bonus - typescript now is supported, more info here https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/
